# Generated by Django 3.0.8 on 2020-09-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('nike', 'nike'), ('addidas', 'addidas'), ('rainbow', 'rainbow'), ('vans', 'vans'), ('other', 'other')], default='vans', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FastenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastener', models.CharField(choices=[('laces', 'laces'), ('velcrow', 'velcrow'), ('other', 'other')], default='laces', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('black', 'black'), ('white', 'white')], default='white', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('leather', 'leather'), ('canvas', 'canvas'), ('other', 'other')], default='leather', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='7', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('sneaker', 'sneaker'), ('boot', 'boot'), ('sandal', 'sandal'), ('dress', 'dress'), ('other', 'other')], default='sneaker', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BrandName')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShoeColor')),
                ('fastener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.FastenType')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Manufacturer')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShoeMaterial')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShoeType')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShoeSize')),
            ],
        ),
    ]
